type = "javascript"
name = "cms-headless"
workers_dev = true
# Add your account ID here
account_id = "ab41dac3c361e6d9cadaeb1888cd9945"

[build]
command = "npm run build"
watch_dir = "worker"

[build.upload]
format = "service-worker"
main = "./index.js"
dir = "./build"

[[kv_namespaces]]
binding = "DATABASE"
preview_id = "<ignored>"
id = "<ignored>"
